@Data_Api_HostAddress = http://localhost:5157
GET {{Data_Api_HostAddress}}/

###

GET {{Data_Api_HostAddress}}/maihianyok
###

POST {{Data_Api_HostAddress}}/hiany
Content-Type: application/json

{
  "name":"Próba Emõke",
  "osztaly":"8048b263-4106-4925-a316-ffdee54a91a2",
  "datum":"2023-12-17"
}
###

GET {{Data_Api_HostAddress}}/hianyok/2023-12-16

###

PUT {{Data_Api_HostAddress}}/hiany/5
Content-Type: application/json

{
  "name":"Próba Emõke",
  "osztaly":"10 a.",
  "datum":"2023-12-16",
  "hianyzik":true
}

###

DELETE {{Data_Api_HostAddress}}/hiany/1

###
POST {{Data_Api_HostAddress}}/pont
Content-Type: application/json
{
  "tanuloId":"ad23c929-7c72-4512-93d1-1877fe290b8a",
  "datum":"2025-05-11",
  "jegyzet":"Próba lecke munka",
  "pontSzam":2,
  "pontTipus":0
}
###
GET {{Data_Api_HostAddress}}/pont/1
###
GET {{Data_Api_HostAddress}}/pont/osztaly/8048b263-4106-4925-a316-ffdee54a91a2
###
POST {{Data_Api_HostAddress}}/szorgalmi
Content-Type: application/json
{
  "tanuloId":"ad23c929-7c72-4512-93d1-1877fe290b8a",
  "jegyzet":"Próba szorgalmi munka",
  "pont":2,
  "feladatok_szama":1,
  "osztaly":"8048b263-4106-4925-a316-ffdee54a91a2"
}
