// <auto-generated />
using System;
using Data_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Api.Migrations
{
    [DbContext(typeof(FeladatSQL))]
    [Migration("20260910173439_InitializeCreate")]
    partial class InitializeCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Data_Api.Data.FeladatHiany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<Guid>("FeladatId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Hianyzik")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Osztaly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TanuloId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TanuloId");

                    b.ToTable("FeladatHianyok");
                });

            modelBuilder.Entity("Data_Api.Data.HibasFeladat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Osztaly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TanuloId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TanuloId");

                    b.ToTable("HibasFeladatok");
                });

            modelBuilder.Entity("Data_Api.Data.Pont", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Jegyzet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PontSzam")
                        .HasColumnType("int");

                    b.Property<int>("PontTipus")
                        .HasColumnType("int");

                    b.Property<Guid>("TanuloId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TanuloId");

                    b.ToTable("Pontok");
                });

            modelBuilder.Entity("Data_Api.Data.PontLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PontId")
                        .HasColumnType("int");

                    b.Property<string>("Valtozas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PontLogok");
                });

            modelBuilder.Entity("Data_Api.Data.Szorgalmi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FeladatTipus")
                        .HasColumnType("int");

                    b.Property<int>("Feladatok_szama")
                        .HasColumnType("int");

                    b.Property<string>("Jegyzet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Osztaly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pont")
                        .HasColumnType("int");

                    b.Property<Guid>("TanuloId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TanuloId");

                    b.ToTable("Szorgalmik");
                });

            modelBuilder.Entity("Data_Api.Data.Szoveg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Szovegek");
                });

            modelBuilder.Entity("Data_Api.Data.Tanulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("LastModify")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Osztaly")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Pont")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tanulok");
                });

            modelBuilder.Entity("Data_Api.Data.FeladatHiany", b =>
                {
                    b.HasOne("Data_Api.Data.Tanulo", null)
                        .WithMany("Hianyok")
                        .HasForeignKey("TanuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Api.Data.HibasFeladat", b =>
                {
                    b.HasOne("Data_Api.Data.Tanulo", null)
                        .WithMany("Hibak")
                        .HasForeignKey("TanuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Api.Data.Pont", b =>
                {
                    b.HasOne("Data_Api.Data.Tanulo", null)
                        .WithMany("Pontok")
                        .HasForeignKey("TanuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Api.Data.Szorgalmi", b =>
                {
                    b.HasOne("Data_Api.Data.Tanulo", null)
                        .WithMany("Szorgalmik")
                        .HasForeignKey("TanuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Api.Data.Tanulo", b =>
                {
                    b.Navigation("Hianyok");

                    b.Navigation("Hibak");

                    b.Navigation("Pontok");

                    b.Navigation("Szorgalmik");
                });
#pragma warning restore 612, 618
        }
    }
}
